/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as InterviewNewRouteImport } from './routes/interview.new'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as DashboardResumesRouteImport } from './routes/dashboard.resumes'
import { Route as DashboardPracticeRouteImport } from './routes/dashboard.practice'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InterviewNewRoute = InterviewNewRouteImport.update({
  id: '/interview/new',
  path: '/interview/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumesRoute = DashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeRoute = DashboardPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/resumes': typeof DashboardResumesRoute
  '/interview/$id': typeof InterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/resumes': typeof DashboardResumesRoute
  '/interview/$id': typeof InterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/resumes': typeof DashboardResumesRoute
  '/interview/$id': typeof InterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/interviews'
    | '/dashboard/practice'
    | '/dashboard/resumes'
    | '/interview/$id'
    | '/interview/new'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/interviews'
    | '/dashboard/practice'
    | '/dashboard/resumes'
    | '/interview/$id'
    | '/interview/new'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/interviews'
    | '/dashboard/practice'
    | '/dashboard/resumes'
    | '/interview/$id'
    | '/interview/new'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InterviewIdRoute: typeof InterviewIdRoute
  InterviewNewRoute: typeof InterviewNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/interview/new': {
      id: '/interview/new'
      path: '/interview/new'
      fullPath: '/interview/new'
      preLoaderRoute: typeof InterviewNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resumes': {
      id: '/dashboard/resumes'
      path: '/resumes'
      fullPath: '/dashboard/resumes'
      preLoaderRoute: typeof DashboardResumesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/practice': {
      id: '/dashboard/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardPracticeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardPracticeRoute: typeof DashboardPracticeRoute
  DashboardResumesRoute: typeof DashboardResumesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardPracticeRoute: DashboardPracticeRoute,
  DashboardResumesRoute: DashboardResumesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InterviewIdRoute: InterviewIdRoute,
  InterviewNewRoute: InterviewNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
